import mongoose from "mongoose";
import { FlightType } from "./types";

// Define the Flight schema
const flightSchema = new mongoose.Schema<FlightType>({
  aircraft_id: { type: String, required: true }, // The ID of the aircraft associated with the flight, required field
  number: { type: String, required: true, unique: true }, // Flight number, must be unique and required
  ori_airport: { type: String, required: true }, // The origin airport of the flight, required field
  des_airport: { type: String, required: true }, // The destination airport of the flight, required field
  scheduled_departure: { type: Date, required: true }, // The scheduled departure date and time, required field
  scheduled_arrival: { type: Date }, // The scheduled arrival date and time (optional field)
  actual_departure: { type: Date }, // The actual departure date and time (optional field)
  actual_arrival: { type: Date }, // The actual arrival date and time (optional field)
  nums_busi_seat_avail: { type: Number, required: true }, // Number of available business class seats, required field
  nums_eco_seat_avail: { type: Number, required: true }, // Number of available economy class seats, required field
  base_price: { type: Number, required: true }, // The base price for the flight, required field
  revenue: { type: Number, default: 0 }, // The total revenue generated by the flight, default to 0
});

// Create and export the Flight model based on the schema
const Flight = mongoose.model<FlightType>("Flight", flightSchema);
export default Flight;
